Remote deployment for make-docs.

diff --git a/portal/bin/make-docs b/portal/bin/make-docs
--- a/portal/bin/make-docs
+++ b/portal/bin/make-docs
@@ -4,7 +4,8 @@
 SCRIPT_ROOT=$(cd -P $(dirname "$0") && cd .. && pwd)
 DOC_ROOT="$SCRIPT_ROOT/doc"
 OUT_ROOT="$SCRIPT_ROOT/build"
-REMOTE_PATH="doc.gameclosure.com:/srv/www/docs.gameclosure.com/public_html"
+REMOTE_USER=$(whoami)
+REMOTE_PATH="doc.gameclosure.com:/srv/www/docs.gameclosure.com/public_html/"
 CONF_ROOT="$SCRIPT_ROOT/conf"
 INCLUDE_ROOT="$CONF_ROOT/include"
 
@@ -12,7 +13,8 @@ INCLUDE_ROOT="$CONF_ROOT/include"
 function print_help {
 		echo "Usage: $(basename $0) [options]"
 		echo " -D       Deploy to remote."
-		echo " -P=path  Remote path. Default: $REMOTE_PATH"
+		echo " -U=name  Set the remote user name; use with -D. Default: $REMOTE_USER"
+		echo " -R=path  Set the remote path; use with -D. Default: $REMOTE_PATH"
 		echo " -i=dir   Input directory. Default $DOC_ROOT"
 		echo " -o=dir   Output directory. Default: $OUT_ROOT"
 		echo " -h       Print this help."
@@ -47,10 +49,11 @@ function convert_directory {
 		done < <(find "$DOC_ROOT" -type f -name '*.md' | grep -v -i 'readme')
 }
 
-while getopts "DP:i:o:h" opt; do
+while getopts "DR:i:o:h" opt; do
     case $opt in
 				D) DEPLOY_FLAG=1;;
-				P) REMOTE_PATH="$OPTARG";;
+				U) REMOTE_USER="$OPTARG";;
+				R) REMOTE_PATH="$OPTARG";;
 				i) DOC_ROOT="$OPTARG";;
 				o) OUT_ROOT="$OPTARG";;
 				h) print_help; exit 0;;
@@ -79,7 +82,7 @@ if [ ! -d "$OUT_ROOT" ]; then
 		mkdir -p "$OUT_ROOT"
 fi
 
-# Off we go ...
+# And off we go ...
 
 echo "  Copying include files ..."
 cp -r "$INCLUDE_ROOT" "$OUT_ROOT"
@@ -88,8 +91,19 @@ cp -r "$INCLUDE_ROOT" "$OUT_ROOT"
 m4 -P -D sidebar_nav="$CONF_ROOT/sidebar-nav.html" \
 		"$CONF_ROOT/template.html" > "$CONF_ROOT/template.html.tmp"
 
+## Convert files from markdown to html and output ...
 convert_directory
 
+## Sync with remote ...
+if [ -n "$DEPLOY_FLAG" ]; then
+		if ! which rsync > /dev/null; then
+				echo "Error: Unable to locate rsync, no remote deployment."
+		else
+				#requires traling slash
+				echo "Syncing with remote directory ..."
+				rsync -rzvh --omit-dir-times --archive --delete "$OUT_ROOT/" "$REMOTE_USER@$REMOTE_PATH"
+		fi
+fi
 
 ## Cleanup ...
 if [ -f "$CONF_ROOT/template.html.tmp" ]; then
